# Generated by Django 4.2.1 on 2023-05-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number', models.CharField(max_length=255)),
                ('vehicle', models.CharField(choices=[('ELECTRIQUE', 'Electrique'), ('DIESEL', 'Diesel'), ('ESSENCE', 'Essence')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autopark.location')),
            ],
        ),
    ]
