# Generated by Django 4.2.1 on 2023-05-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle',
            new_name='vehicle_type',
        ),
    ]
